#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    DO \$\$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${JAVA_SERVICE_DB_USER}') THEN
            CREATE USER ${JAVA_SERVICE_DB_USER} WITH PASSWORD '${JAVA_SERVICE_DB_PASSWORD}';
        END IF;
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${PYTHON_SERVICE_DB_USER}') THEN
            CREATE USER ${PYTHON_SERVICE_DB_USER} WITH PASSWORD '${PYTHON_SERVICE_DB_PASSWORD}';
        END IF;
    END
    \$\$;

    GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${JAVA_SERVICE_DB_USER}, ${PYTHON_SERVICE_DB_USER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    GRANT USAGE, CREATE ON SCHEMA public TO ${JAVA_SERVICE_DB_USER};
    GRANT USAGE ON SCHEMA public TO ${PYTHON_SERVICE_DB_USER};

    GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO ${JAVA_SERVICE_DB_USER};
    GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO ${JAVA_SERVICE_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${JAVA_SERVICE_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${JAVA_SERVICE_DB_USER};

    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${PYTHON_SERVICE_DB_USER};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${PYTHON_SERVICE_DB_USER};
EOSQL
