"""
Module: ai
SQLAlchemy 2.x ORM models for the ai module.

Enums are defined inline in this file.

Entity defined here:
- PredictionIA → Written exclusively by python-service AI module.
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import UUID as PythonUUID

from sqlalchemy import Boolean, Enum as SAEnum, Numeric, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class ModeleIA(str, enum.Enum):
    """AI model type used to produce this prediction."""
    ISOLATION_FOREST = "ISOLATION_FOREST"
    REGRESSION = "REGRESSION"


class PredictionIA(Base):
    """
    Module: ai
    Table SQL: prediction_ia

    Written BY: python-service (AI module — Isolation Forest & Regression models).
    Read BY: java-service in read-only mode for frontend display (history, KPIs).

    IMPORTANT: java-service never writes to this table.
    id_mesure is stored as a plain UUID to avoid FK coupling with the mesure table
    (already managed by the plc module).

    The UUID PK is always generated by the database, never by Python, to maintain
    consistency with java-service reads on shared tables.
    """

    __tablename__ = "prediction_ia"

    id_prediction: Mapped[PythonUUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    # Plain UUID reference to mesure.id_mesure.
    id_mesure: Mapped[PythonUUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )
    modele_utilise: Mapped[str] = mapped_column(
        SAEnum(ModeleIA, name="modele_ia_enum", create_type=False),
        nullable=False,
    )
    valeur_predite: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 2), nullable=True
    )
    valeur_reelle: Mapped[Optional[Decimal]] = mapped_column(
        Numeric(6, 2), nullable=True
    )
    est_anomalie: Mapped[Optional[bool]] = mapped_column(Boolean, nullable=True)
    date_prediction: Mapped[datetime] = mapped_column(
        nullable=False, server_default=text("now()")
    )
    updated_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)
    deleted_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)
