/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReinitialiserMotDePasseRouteImport } from './routes/reinitialiser-mot-de-passe'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ActivationRouteImport } from './routes/activation'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSuperviseursRouteImport } from './routes/_authenticated/superviseurs'
import { Route as AuthenticatedSeuilsRouteImport } from './routes/_authenticated/seuils'
import { Route as AuthenticatedPlcRouteImport } from './routes/_authenticated/plc'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAlertesRouteImport } from './routes/_authenticated/alertes'

const ReinitialiserMotDePasseRoute = ReinitialiserMotDePasseRouteImport.update({
  id: '/reinitialiser-mot-de-passe',
  path: '/reinitialiser-mot-de-passe',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivationRoute = ActivationRouteImport.update({
  id: '/activation',
  path: '/activation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperviseursRoute =
  AuthenticatedSuperviseursRouteImport.update({
    id: '/superviseurs',
    path: '/superviseurs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSeuilsRoute = AuthenticatedSeuilsRouteImport.update({
  id: '/seuils',
  path: '/seuils',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlcRoute = AuthenticatedPlcRouteImport.update({
  id: '/plc',
  path: '/plc',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertesRoute = AuthenticatedAlertesRouteImport.update({
  id: '/alertes',
  path: '/alertes',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/activation': typeof ActivationRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/alertes': typeof AuthenticatedAlertesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/plc': typeof AuthenticatedPlcRoute
  '/seuils': typeof AuthenticatedSeuilsRoute
  '/superviseurs': typeof AuthenticatedSuperviseursRoute
}
export interface FileRoutesByTo {
  '/activation': typeof ActivationRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/alertes': typeof AuthenticatedAlertesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/plc': typeof AuthenticatedPlcRoute
  '/seuils': typeof AuthenticatedSeuilsRoute
  '/superviseurs': typeof AuthenticatedSuperviseursRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/activation': typeof ActivationRoute
  '/change-password': typeof ChangePasswordRoute
  '/login': typeof LoginRoute
  '/reinitialiser-mot-de-passe': typeof ReinitialiserMotDePasseRoute
  '/_authenticated/alertes': typeof AuthenticatedAlertesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/plc': typeof AuthenticatedPlcRoute
  '/_authenticated/seuils': typeof AuthenticatedSeuilsRoute
  '/_authenticated/superviseurs': typeof AuthenticatedSuperviseursRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activation'
    | '/change-password'
    | '/login'
    | '/reinitialiser-mot-de-passe'
    | '/alertes'
    | '/dashboard'
    | '/history'
    | '/plc'
    | '/seuils'
    | '/superviseurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activation'
    | '/change-password'
    | '/login'
    | '/reinitialiser-mot-de-passe'
    | '/alertes'
    | '/dashboard'
    | '/history'
    | '/plc'
    | '/seuils'
    | '/superviseurs'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/activation'
    | '/change-password'
    | '/login'
    | '/reinitialiser-mot-de-passe'
    | '/_authenticated/alertes'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/plc'
    | '/_authenticated/seuils'
    | '/_authenticated/superviseurs'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ActivationRoute: typeof ActivationRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  LoginRoute: typeof LoginRoute
  ReinitialiserMotDePasseRoute: typeof ReinitialiserMotDePasseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reinitialiser-mot-de-passe': {
      id: '/reinitialiser-mot-de-passe'
      path: '/reinitialiser-mot-de-passe'
      fullPath: '/reinitialiser-mot-de-passe'
      preLoaderRoute: typeof ReinitialiserMotDePasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activation': {
      id: '/activation'
      path: '/activation'
      fullPath: '/activation'
      preLoaderRoute: typeof ActivationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superviseurs': {
      id: '/_authenticated/superviseurs'
      path: '/superviseurs'
      fullPath: '/superviseurs'
      preLoaderRoute: typeof AuthenticatedSuperviseursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/seuils': {
      id: '/_authenticated/seuils'
      path: '/seuils'
      fullPath: '/seuils'
      preLoaderRoute: typeof AuthenticatedSeuilsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plc': {
      id: '/_authenticated/plc'
      path: '/plc'
      fullPath: '/plc'
      preLoaderRoute: typeof AuthenticatedPlcRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alertes': {
      id: '/_authenticated/alertes'
      path: '/alertes'
      fullPath: '/alertes'
      preLoaderRoute: typeof AuthenticatedAlertesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAlertesRoute: typeof AuthenticatedAlertesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedPlcRoute: typeof AuthenticatedPlcRoute
  AuthenticatedSeuilsRoute: typeof AuthenticatedSeuilsRoute
  AuthenticatedSuperviseursRoute: typeof AuthenticatedSuperviseursRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAlertesRoute: AuthenticatedAlertesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedPlcRoute: AuthenticatedPlcRoute,
  AuthenticatedSeuilsRoute: AuthenticatedSeuilsRoute,
  AuthenticatedSuperviseursRoute: AuthenticatedSuperviseursRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ActivationRoute: ActivationRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  LoginRoute: LoginRoute,
  ReinitialiserMotDePasseRoute: ReinitialiserMotDePasseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
