"""
Module: plc
SQLAlchemy 2.x ORM models for the plc module.

This file defines:
- Mesure (collected sensors metrics)
- ConfigurationPLC (PLC configuration IP/rack/slot/polling interval)
"""

from __future__ import annotations

import enum
from datetime import datetime
from decimal import Decimal
from typing import Optional

from sqlalchemy import Boolean, Enum as SAEnum, Integer, Numeric, String, select, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, Session, mapped_column


class Base(DeclarativeBase):
    pass


class Metrique(str, enum.Enum):
    """Metric types collected from PLC sensors."""
    TEMPERATURE = "TEMPERATURE"
    HUMIDITE = "HUMIDITE"


class Mesure(Base):
    """
    Module: plc
    Table SQL: mesure

    Written BY: python-service (PLC ingestion — this is the primary writer).
    Read BY: java-service (KPIs, history display, alerting triggers) in read-only mode.

    This table is the single source of truth for raw sensor data. All alerting,
    AI predictions, and Java KPI endpoints read from this table.

    IMPORTANT: The UUID is generated by the database (gen_random_uuid()), not by Python,
    so that it stays consistent with any java-service reads on shared tables.
    """

    __tablename__ = "mesure"

    id_mesure: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    metrique: Mapped[str] = mapped_column(
        SAEnum(Metrique, name="metrique_enum", create_type=False),
        nullable=False,
    )
    valeur: Mapped[Decimal] = mapped_column(
        Numeric(precision=6, scale=2),
        nullable=False,
    )
    identifiant_caisse: Mapped[Optional[str]] = mapped_column(
        String(100),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=text("now()"),
    )


class ConfigurationPLC(Base):
    """
    Module: plc
    Table SQL: configuration_plc

    Table ÉCRITE EXCLUSIVEMENT par java-service (Admin configure via l'interface).
    Python LIT SEULEMENT cette table au démarrage du service PLC pour établir la
    connexion Snap7/OPC UA (plc_ip, plc_rack, plc_slot, plc_polling_interval_ms).

    Ne jamais appeler session.add()/commit() sur cette entité depuis python-service.
    """

    __tablename__ = "configuration_plc"

    id_configuration: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )
    id_admin: Mapped[UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
    )
    plc_ip: Mapped[str] = mapped_column(
        String(45),
        nullable=False,
    )
    plc_rack: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )
    plc_slot: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )
    plc_polling_interval_ms: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
    )
    actif: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        server_default=text("true"),
    )
    created_at: Mapped[datetime] = mapped_column(
        nullable=False,
        server_default=text("now()"),
    )


def get_active_plc_config(session: Session) -> Optional[ConfigurationPLC]:
    """
    Returns the currently active PLC configuration (where actif=True).
    Used at startup of the plc module.
    """
    return session.execute(
        select(ConfigurationPLC).where(ConfigurationPLC.actif == True)
    ).scalar_one_or_none()
