package com.projet.audit.model.enums;

public enum ActionAudit {
    CONNEXION,
    DECONNEXION,
    TENTATIVE_CONNEXION_ECHOUEE,
    CREATION_SUPERVISEUR,
    COMPTE_ACTIVE_SUPERVISEUR,
    ACTIVATION_SUPERVISEUR,
    MODIFICATION_SUPERVISEUR,
    DESACTIVATION_SUPERVISEUR,
    EXPORT_MESURES,
    GENERER_RAPPORT,
    TELECHARGEMENT_RAPPORT,
    MODIFICATION_CONFIGURATION_PLC,
    MODIFICATION_CONFIGURATION_SEUILS
}
