package com.projet.audit.model.enums;

public enum ActionAudit {
    CONNEXION,
    DECONNEXION,
    CREATION_UTILISATEUR,
    MODIFICATION_UTILISATEUR,
    DESACTIVATION_UTILISATEUR,
    MODIFICATION_DESTINATAIRE_NOTIFICATION,
    VALIDATION_ANOMALIE,
    EXPORT_DONNEES,
    TELECHARGEMENT_RAPPORT,
    TENTATIVE_CONNEXION_ECHOUEE,
    MODIFICATION_CONFIGURATION_SYSTEME
}
